import { Suspense, createElement } from 'react'
//import HeaderTop from '@/components/HeaderTop/page';
import dynamic from 'next/dynamic'
import ScrollComponent from '../components/ScrollComponent/page';
//import ToggleHeader from '../components/ToggleHeader/page';
//import { NavigationEvents } from '../components/NavigationsEvents/page';
import Link from 'next/link';
//import Button from '@/components/Button/page';
//import { buttonClick } from "@/app/actions/updateStatus";
//import { getItemData } from "@/app/actions/getItemData";
import './globals.css'
import styles from "./page.module.css";
//import Form from 'next/form';
//import { buttonClick } from './actions/toggleClickjs';
import Image from "next/image";
import bigImage from "./big.svg";
import { Passion_One } from 'next/font/google';

const passion = Passion_One({
  subsets: ['latin'],
  display: 'swap',
  style: "normal",
  weight: "400"
});

//import Image from 'next/image';
//import myGif from '@/styles/8.gif'
//import Loader from "react-loader-spinner";
//import "react-loader-spinner/dist/loader/css/react-spinner-loader.css";
/*const IOComponent = dynamic(() => import('../components/IOComponent/page'), {
  loading: () => <span>Loading...</span>, ssr: false
})*/
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
//<main>

export default async function Layout(props) {
  //<nav className={styles.labelWrapper} >
  //console.log('rootLayout',params)//undef
  /*<main className={styles.headerToggle}>
            <nav>
              <Link href="/categories/main" scroll={false}
                className={styles.km}>в километрах</Link>
              <span className={styles.space}>|</span>
              <Link href="/categories/moon" scroll={false}
                className={styles.moon}>в лунных орбитах</Link>
              <Link href="/categories/marked" scroll={false}
                className={styles.footer}>Отправить</Link>
            </nav>
          </main>*/
  return (
    <html lang="ru">
      <body>
        <div key='next' id='__next'>
          <header className={styles.header} id='header'>
            <h1 className={passion.className}>ARMAGEDDON 2023</h1>
            <div className={styles.command}>
              <span>
                ООО “Команда им. Б. Уиллиса”.
              </span>
              <span>
                Взрываем астероиды с 1998 года.
              </span>
            </div>
          </header>
          <div className={styles.hidden}>
            <Image src={bigImage} alt="Earth" priority />
          </div>
          <Suspense fallback={<span className={'loader'}></span>}>
            {props.children}
          </Suspense>
          <ScrollComponent />
        </div>
      </body>
    </html >
  )
}
