import { Suspense, createElement } from 'react'
//import HeaderTop from '@/components/HeaderTop/page';
import dynamic from 'next/dynamic'
import ScrollComponent from '../components/ScrollComponent/page';
//import Button from '@/components/Button/page';
//import { buttonClick } from "@/app/actions/updateStatus";
//import { getItemData } from "@/app/actions/getItemData";
import styles from "./page.module.css";
import Form from 'next/form';
import { buttonClick } from './actions/updateStatus';
import Image from "next/image";
import bigImage from "./big.svg";

//import Image from 'next/image';
//import myGif from '@/styles/8.gif'
//import Loader from "react-loader-spinner";
//import "react-loader-spinner/dist/loader/css/react-spinner-loader.css";
/*const IOComponent = dynamic(() => import('../components/IOComponent/page'), {
  loading: () => <span>Loading...</span>, ssr: false
})*/
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
//<Form action={buttonClick}>
//<main>
              //fill //Image

export default function Layout(props) {
  return (
    <html lang="ru">
      <body>
        <div key='next' id='__next'>
          <header className={styles.header}>
            <h1 className={styles.armageddon}>ARMAGEDDON 2023</h1>
            <div className={styles.command}>
              <span>
                ООО “Команда им. Б. Уиллиса”.
              </span>
              <span>
                Взрываем астероиды с 1998 года.
              </span>
            </div>
          </header>
          <div className={styles.image_wrapper}>
            <Image src={bigImage} alt="Earth"
            />
          </div>
          <Suspense fallback={<span className={'loader'}></span>}>
            {props.children}
          </Suspense>
          <ScrollComponent />
        </div>
      </body>
    </html >
  )
}
