import { Suspense, createElement } from 'react'
//import HeaderTop from '@/components/HeaderTop/page';
import dynamic from 'next/dynamic'
import IOComponent from '../components/IOComponent/page'
import IOComponentTop from '../components/IOComponentTop/page'
import MOComponent from '../components/MOComponent/page'

import ScrollComponent from '../components/ScrollComponent/page'
import ScrollComponentTop from '../components/ScrollComponentTop/page'

import VirtualScrollComponent from '../components/VirtualScrollComponent/page'

//import ToggleHeader from '../components/ToggleHeader/page';
//import { NavigationEvents } from '../components/NavigationsEvents/page';
//import Link from 'next/link';
//import Button from '@/components/Button/page';
//import { buttonClick } from "@/app/actions/updateStatus";
//import { getItemData } from "@/app/actions/getItemData";
import './globals.css'
import styles from "./page.module.css";
//import Form from 'next/form';
//import { buttonClick } from './actions/toggleClickjs';
import Image from "next/image";
import bigImage from "./big.svg";
import { Passion_One } from 'next/font/google';

const passion = Passion_One({
  subsets: ['latin'],
  display: 'swap',
  style: "normal",
  weight: "400"
});

//import Image from 'next/image';
//import myGif from '@/styles/8.gif'
//import Loader from "react-loader-spinner";
//import "react-loader-spinner/dist/loader/css/react-spinner-loader.css";
/*const IOComponent = dynamic(() => import('../components/IOComponent/page'), {
  loading: () => <span>Loading...</span>, ssr: false
})*/
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default async function Layout(props) {
  //            <Image src={bigImage} alt="Earth" priority />
  return (
    <html lang="ru">
      <body>
        <div key='next' id='__next'>
          <header className={styles.header} id='header'>
            <h1 className={passion.className}>ARMAGEDDON 2023</h1>
            <div className={styles.command}>
              <span>
                ООО “Команда им. Б. Уиллиса”.
              </span>
              <span>
                Взрываем астероиды с 1998 года.
              </span>
            </div>
          </header>
          <header className={styles.headerToggle}>
            <h6 className={styles.h6}>Ближайшие подлёты астероидов</h6>
          </header>
          <div className='grid'>
            <div className={styles.hidden}>
            </div>
            <Suspense fallback={<span className={'loader'}></span>}>
              {props.children}
            </Suspense>
          </div>
          <Suspense><IOComponent /></Suspense>
        </div>
      </body>
    </html >
  )
}
