import styles from "./page.module.css";
import Form from "next/form";
import Link from "next/link";
//import { marked } from "../../../actions/marked"


export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function BasketLayout({
    children,
}/*: {
    children: React.ReactNode
}*/) {
    return (
        <output className={styles.padding_count}>{children}</output>
    )
}
