import styles from "./page.module.css";
import Form from "next/form";
import Link from "next/link";
//import { marked } from "../../../actions/marked"


export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function BasketLayout({
    children,
}/*: {
    children: React.ReactNode
}*/) {
    return (
        <footer className={styles.footer}>
            <div className={styles.column}>
                <span className={styles.h3}>Корзина</span>
                <span className={styles.aster}>{children}астероида</span>
            </div>
            <nav className={styles.rrrr}>
                <Link href="/marked" scroll={false}
                    className={styles.button}>
                    <span className={styles.padding}>Отправить</span>
                </Link>
            </nav>
        </footer>
    )
}
