export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function BasketLayout({
    children,
}/*: {
    children: React.ReactNode
}*/) {
    return (
        <output>
            {children}
        </output>
    )
}
